-- Extensión oficial `mcp` (S41): integración de servidores **MCP** (Model
-- Context Protocol) como tools del agente.
--
-- Implementa la **capa 2** de [arquitectura.md](../../../../docs/arquitectura.md)
-- ("Procesos externos vía subproceso, JSON-RPC/stdio. MCP vive aquí, implementado
-- como extensión oficial Lua sobre las primitivas `io.spawn` + codecs: el core no
-- sabe qué es MCP"). Cierra la **cuestión abierta nº4** de arquitectura.md (el
-- contrato de la extensión MCP: formato de configuración, ciclo de vida de los
-- procesos, mapeo de tools y de su confianza).
--
-- ADR-003: el core NO sabe lo que es MCP; todo es Lua puro sobre la API pública
-- congelada ([api.md](../../../../docs/api.md)) —`enu.proc` (§6, S16) para lanzar y
-- hablar con el servidor por stdio, `enu.json` (§12, S18) para JSON-RPC 2.0,
-- `enu.task` (§4) para el ciclo de vida y el demultiplexado de respuestas— y sobre
-- la extensión `agent` (S39, en `requires`): cada tool que el servidor anuncia se
-- registra con `agent.tool{...}` exactamente igual que una tool de fichero
-- (agente.md §3: "MCP encaja aquí sin caso especial"). Sin privilegio de kernel.
--
-- El `init.lua` solo CABLEA: deja el módulo público accesible por `require`. La
-- API de consumo (`mcp.connect`, `mcp.servers`...) la expone el módulo `mcp`,
-- requerible por `chat` (S43) y cualquier extensión/script con `require("mcp")`.
--
-- NO se conecta a ningún servidor al cargar: un servidor MCP es un proceso externo
-- y lanzarlo es un acto del usuario/host (vía `mcp.toml` o `mcp.connect`
-- explícito). Cargar la extensión solo expone la maquinaria (el módulo `mcp` lo
-- registra el loader antes de correr ningún init, §14; este `init.lua` no necesita
-- requerirlo).
--
-- NO HAY AUTO-CONNECT AL CARGAR (G59). Antes, este `init.lua` spawneaba una task que
-- llamaba a `mcp.connect_configured`; pero esa task es EFÍMERA y corre DENTRO del
-- drenaje de `Boot` (RunTasks a quiescencia de primer plano), así que su
-- `enu.task.cleanup` cerraba las conexiones y stubbeaba las tools ANTES de que
-- arrancara el turno de `enu -p` —dejándolas inservibles en headless— y también antes
-- del pump interactivo. Una task que sobreviviera a `Boot` lo bloquearía (RunTasks la
-- espera), y no hay superficie pública para una task de FONDO. Por eso el auto-connect
-- headless lo orquesta ahora el PRODUCTO (el driver del CLI, `cmd/enu/main.go`) en la
-- MISMA task del turno, ANTES de `agent.session`: la conexión vive lo que el turno y
-- se cierra al terminarlo. El auto-connect INTERACTIVO queda pendiente (G64). Ver el
-- hallazgo [G59](../../../../../docs/findings/g59-el-auto-connect-de-mcp-toml.md).
